language: rust
rust:
  - nightly
os:
  - linux
dist: jammy
arch:
  - amd64
cache: cargo
before_install:
  - sudo apt-get update -y
install:
  - cargo install rustfilt
  - rustup component add llvm-tools-x86_64-unknown-linux-gnu
  - go install github.com/itchyny/gojq/cmd/gojq@latest
script:
  - cargo test
  - echo hi
  # - cmake --build ./build
  # - make -C ./build test codecov && echo "$CODECOV_TOKEN" > ./build/cct && bash <(curl -s https://codecov.io/bash) -f ./build/codecov.xml -t @./build/cct